# Generated by Django 5.1.3 on 2024-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('Department', models.CharField(max_length=50)),
                ('Doctor', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
